version: '3.8'

services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts:/docker-entrypoint-initdb.d 
    ports:
      - "5432:5432"

volumes:
  postgres_data:
